### ISSUE TITLE
更新新版本后, 不会同步到todoist上

### ISSUE THREAD

**Issue by musicleaf** [HeroBlackInk/ultimate-todoist-sync-for-obsidian#10]
<img width="653" alt="image" src="https://user-images.githubusercontent.com/35360006/233767698-7ad9a42a-0e60-4d85-aed2-0ea819c792e4.png">

恢复上一个版本就会同步

<img width="783" alt="image" src="https://user-images.githubusercontent.com/35360006/233768071-fd6d638e-2179-45fc-b5cb-d3e249cf5e0f.png">

**Comment by putink** [comment]
我也遇到了同样的问题,去掉图标与日期之间的空格，不发同步
![image](https://user-images.githubusercontent.com/22392907/233772739-dcca364b-d5b0-4129-ac5e-dc7ebf1c43e9.png)

**Comment by putink** [comment]
> 我也遇到了同样的问题,去掉图标与日期之间的空格，不发同步 ![image](https://user-images.githubusercontent.com/22392907/233772739-dcca364b-d5b0-4129-ac5e-dc7ebf1c43e9.png)

2 没有创建新的todoist id

**Comment by HeroBlackInk** [comment]
solved 506c7e2c99458fc854e2f1c4430edcee6e8ec993
