### ISSUE TITLE
Failed to load plugin

### ISSUE THREAD

**Issue by Klaudioz** [HeroBlackInk/ultimate-todoist-sync-for-obsidian#12]
After following the instructions I'm getting:

Failed to load plugin ultimate-todoist-sync (1.0.35)

I'm using Obsidian v1.2.5

**Comment by HeroBlackInk** [comment]
The new version release has been revoked, please use 1.0.33

**Comment by Klaudioz** [comment]
I got the same with that version after restarting Obsidian:

![image](https://user-images.githubusercontent.com/632625/233787619-65999b9a-03b9-446f-a22e-4d313874e9ab.png)

**Comment by HeroBlackInk** [comment]
I have not encountered this problem, and currently no one else has reported such a problem. Without detailed information, I cannot help you.

**Comment by Klaudioz** [comment]
What details do you need?

**Comment by HeroBlackInk** [comment]
You can open the developer tool and check the console output.

**Comment by Klaudioz** [comment]
`Plugin failure: ultimate-todoist-sync Error: ENOENT: no such file or directory, open '/Users/canalescl/Library/Mobile Documents/iCloud~md~obsidian/Documents/obsidian/.obsidian/plugins/ultimate-todoist-sync-for-obsidian-1.0-1.33/main.js'`

![image](https://user-images.githubusercontent.com/632625/233788717-8922804e-e0d3-4978-acf6-c7c8009daaa4.png)

**Comment by HeroBlackInk** [comment]
plugin folder name is u**ltimate-todoist-sync**,Other names are not allowed

**Comment by Klaudioz** [comment]
I got the same after changing the name:

`Plugin failure: ultimate-todoist-sync Error: ENOENT: no such file or directory, open '/Users/canalescl/Library/Mobile Documents/iCloud~md~obsidian/Documents/obsidian/.obsidian/plugins/ultimate-todoist-sync/main.js'`

**Comment by HeroBlackInk** [comment]
Please download the release, your cloned source code does not have the main.js file. It cannot run.

**Comment by Klaudioz** [comment]
I did it.

The file: https://github.com/HeroBlackInk/ultimate-todoist-sync-for-obsidian/archive/refs/tags/1.0.33.zip is containing the main.ts file on the root of the folder.

**Comment by HeroBlackInk** [comment]
The download you have is the source code release, not a packaged plugin release.
