### ISSUE TITLE
📅和日期之间有空格的时候无法同步时间到todoist

### ISSUE THREAD

**Issue by JavaYIC** [HeroBlackInk/ultimate-todoist-sync-for-obsidian#14]
感谢作者做出那么好的插件。但是我想要实现task+每日笔记+todoist联动的效果，但是task自动生成的日期带有空格，无法同步到todoist，只有人工把空格去掉才能同步。希望能解决，谢谢！
![image](https://user-images.githubusercontent.com/27794307/234434927-dcc25534-2b24-4bb6-be2b-cae3c91402fd.png)
![image](https://user-images.githubusercontent.com/27794307/234434955-6be0ec08-fb92-4e87-b6f7-9307ac8ac606.png)

**Comment by HeroBlackInk** [comment]
语法规范参考的 dataview的标准，没有兼容其他插件的计划。。。

**Comment by JavaYIC** [comment]
原来是这样，那大佬可不可以指导一下在哪修改，我为了这个空格，学regex学了一天，折腾了好久都没搞定😂

**Comment by HeroBlackInk** [comment]
clone 代码，使用vscode搜索日历emoji ，修改相关代码。。regex不用学，直接问gpt。。

改起来可能有点麻烦，因为task 文本包含很多内容，我是通过空格和正则表达式处理的，加入一个空格可能会有别的问题。

**Comment by JavaYIC** [comment]
嗯嗯，感谢大佬。

**Comment by HeroBlackInk** [comment]
编译插件 npm run dev
