### ISSUE TITLE
使用同名标记指定特定项目，但是todo相应项目中没有出现

### ISSUE THREAD

**Issue by kk-ssh** [HeroBlackInk/ultimate-todoist-sync-for-obsidian#17]
如题，在收集箱中，不在标签对应项目中。
![Uploading 1682667129896.png…]()

**Comment by HeroBlackInk** [comment]
没有任何信息，无法提供帮助。请给出bug复现的详细过程和截图。。

**Comment by kk-ssh** [comment]
![Quicker_20230505_181453](https://user-images.githubusercontent.com/58595738/236433219-bc938d0f-879b-4a48-ba3e-e0f5b679490b.png)
这是我在ob里写的
![1683282124664](https://user-images.githubusercontent.com/58595738/236433635-f0acd5d5-5e3c-46fb-8505-d46f46c7217d.png)
这是todoist呈现出来的

**Comment by kk-ssh** [comment]
todoist中有同名项目，但是它仍然放在了收件箱中。
![image](https://user-images.githubusercontent.com/58595738/236433801-6894c2db-0fba-4a0a-b650-e414860020b1.png)
而且我想实现如示例中那样下拉式的任务列表，也没有实现。
然后我还有个疑惑，时间是必须用示例中的图标才能被识别吗？

**Comment by HeroBlackInk** [comment]
不够详细。。
1. 什么情况下会同步问题？
2. 每次都出问题还是偶尔出问题？
3. 其他项目是否同步正常？
4. 你是否在设置中手动点击了Sync Projects ?当你在todoist中添加了新的项目，插件不会自动同步到Obsidian，会认为该项目不存在，

**Comment by HeroBlackInk** [comment]
关于图标问题，请仔细阅读文档。。

**Comment by HeroBlackInk** [comment]
子任务我测试是正常的，必须使用tab键缩进。

**Comment by HeroBlackInk** [comment]
你这应该是用 tasks插件生成的， 📅后面多了个空格，和我的插件格式不一样，你需要手动删除📅后面的空格才能识别

**Comment by kk-ssh** [comment]
> 我刚点击了Sync Projects，任务仍然留在收件箱中，没有转移到项目里。这个问题一直存在，我还没有成功标记过。
![1683283549204](https://user-images.githubusercontent.com/58595738/236438159-b116d2a3-31b2-4243-b97d-6c390cddd7f9.png)

**Comment by HeroBlackInk** [comment]
task 只能在添加的时候指定项目。无法转移。你需要删除任务，重新添加。

我刚刚又试了试，指定项目tag，添加成功，没有任何问题。

**Comment by kk-ssh** [comment]
谢谢解答

**Comment by HeroBlackInk** [comment]
如果你脸
