### ISSUE TITLE
Due date does not populate properly in todoist

### ISSUE THREAD

**Issue by PixelPoxel** [HeroBlackInk/ultimate-todoist-sync-for-obsidian#18]
The Duedate added to obsidian is populating as text in todoist, not as a actual due date for the task in todoist

**Obsidian Entry**
![Screenshot 2023-05-04 at 12 41 51 AM](https://user-images.githubusercontent.com/132498914/236020392-4d34d1c9-ffbc-4a6b-be45-4955922eeaf6.png)

**Todoist View**
<img width="545" alt="Screenshot 2023-05-04 at 12 42 03 AM" src="https://user-images.githubusercontent.com/132498914/236020494-c466e63a-42f1-4307-a06a-b25d57173c48.png">

**Comment by PixelPoxel** [comment]
<img width="907" alt="Screenshot 2023-05-04 at 12 54 44 AM" src="https://user-images.githubusercontent.com/132498914/236023711-6e8ebcfe-cea5-427c-a083-d44a0a6c8828.png">

**Comment by HeroBlackInk** [comment]
There must be a space before the calendar emoji.

**Comment by PixelPoxel** [comment]
![Screenshot 2023-05-04 at 9 50 39 PM](https://user-images.githubusercontent.com/132498914/236264467-cd94f60c-948d-4f7e-9f86-78493d1f9b5f.png)

**Comment by HeroBlackInk** [comment]
I have not encountered this problem, and currently no one else has reported such a problem. Without detailed information, I cannot help you.

**Comment by HeroBlackInk** [comment]
I understand, because the date format of the task is different, there is a space after the calendar emoji.

**Comment by PixelPoxel** [comment]
What other detailed information do you need?


> I have not encountered this problem, and currently no one else has reported such a problem. Without detailed information, I cannot help you.

What other detailed information do you need? 
I am using the exact same format you have suggested in your documentation. What am i doing wrong?

**Comment by HeroBlackInk** [comment]
There is a space behind the calendar emoji of the task plug-in, which needs to be deleted manually.

**Comment by PixelPoxel** [comment]
yea, just figured that out. thanks.
Can we fix the plugin to accept the extra space after the emoji? 

I am using the [Obsidian tasks plugin](https://publish.obsidian.md/tasks/Introduction) to create tasks and manage them within Obsidian. 
The tasks plugin automatically inserts a space while adding due dates.
manually trying to delete the space can be time consuming.

BTW, love your plugin. It is solving a major issue for my productivity workflow. thanks for creating this.

**Comment by cyanalpaca003** [comment]
I second that !! Love this plugin. 

Can  you please consider accepting extra space after the calendar emoji? I am using Task plugin on obsidian as well.
