### ISSUE TITLE
Auto Sync all tasks if default project for the file is set

### ISSUE THREAD

**Issue by PixelPoxel** [HeroBlackInk/ultimate-todoist-sync-for-obsidian#19]
If a project page has multiple tasks e.g. 25 tasks, manually adding "#todoist" is too time-consuming.

if the default project is set for a file, then automatically sync all tasks in the file. without the need for "#todoist".

it is also easy to forget adding the #todoist tag, if you are trying to add multiple tasks e.g. capturing tasks during a meeting.

<img width="710" alt="command-set-default-project-for-file" src="https://user-images.githubusercontent.com/132498914/236021963-89cb6a72-73cd-41b3-887d-1539bcc98b8d.png">

**Comment by HeroBlackInk** [comment]
Full vault sync option added in release 1.0.37-beta, automatically adding `#todoist` to all tasks.
