### ISSUE TITLE
Support for dataview/ tasks plugin syntax for dates

### ISSUE THREAD

**Issue by rushikb** [HeroBlackInk/ultimate-todoist-sync-for-obsidian#25]
Hi there, 
love this plugin! Small request, but I noticed that the syntax for adding dates is currently 📅YYYY-MM-DD (no space between the emoji and the date) — I was wondering if it might be possible to also support the dataview/ tasks plugin format for dates. which is 
📅(space)YYYY-MM-DD.  I

**Comment by jun6lee** [comment]
This would make it a great companion to the other popular Obsidian tasks-relates plugins that are already pretty established

**Comment by erleijen** [comment]
I agree with this: by using the same syntax for both plug-ins its usage will be so much more fluid. I was already able to get the due dates synched by adding the space behind the 📆 calendar icon in the main.js file. But it would be great if also the priority fields could be similar.

**Comment by HeroBlackInk** [comment]
It will be supported in the next version update.

**Comment by HeroBlackInk** [comment]
1.0.38 beta now supports date formats for tasks.
