### ISSUE TITLE
Sub Project Support

### ISSUE THREAD

**Issue by jun6lee** [HeroBlackInk/ultimate-todoist-sync-for-obsidian#28]
Eg: I have Projects set up as:

#Work
#Work/Read
#Work/Process

It only picks up Work and adds the rest into description

**Comment by HeroBlackInk** [comment]
There is no difference between subproject and parent project. You just need to use `#Process`.

**Comment by jun6lee** [comment]
It doesn't work. Equating this to https://github.com/HeroBlackInk/ultimate-todoist-sync-for-obsidian/issues/62 
#Process puts it under "Work" but under (No Section)
