### ISSUE TITLE
Plugin not syncing

### ISSUE THREAD

**Issue by jpralle** [HeroBlackInk/ultimate-todoist-sync-for-obsidian#29]
Hi,

I just installed v1.0.36 of the plugin into my Obsidian v1.3.5. I entered my Todoist API key and synced the projects and selected a default project. All of that worked fine. But when I press the sync button in the sidebar, nothing happens. No message, no tasks in Todoist, nothing the in Chrome DevTools console. Not sure where else I can look for information. Any idea what might be wrong?

**Comment by jpralle** [comment]
Even if I click into an note containing tasks, the sync does not seem to do anything. Does the note have to be in edit mode or something?

**Comment by HeroBlackInk** [comment]
I think you didn't read the document carefully.

**Comment by HeroBlackInk** [comment]
Tasks without `#todoist` tag will not be synchronized.

**Comment by jpralle** [comment]
Got it, thank you. A question regarding the full sync from the current beta: Will this not only add the tag to any task but also sync todos from not open files?

**Comment by HeroBlackInk** [comment]
Yes

**Comment by HeroBlackInk** [comment]
1.0.38 beta now supports date formats for tasks.

**Comment by jpralle** [comment]
![Bildschirmfoto 2023-06-21 um 16 33 32](https://github.com/HeroBlackInk/ultimate-todoist-sync-for-obsidian/assets/2845414/9ac36045-09a7-4187-b29a-b777588ecf94)

![Bildschirmfoto 2023-06-21 um 16 35 22](https://github.com/HeroBlackInk/ultimate-todoist-sync-for-obsidian/assets/2845414/d7330419-bb3a-47dd-98a8-7820e9a60dd3)

Thanks :) I updated to 1.0.38. When I add the #todoist to a task, it will sync it correctly to todois, but the due date is not read correctly. Also it somehow does not recognize the due date in Tasks-Plugin correctly. As you can see in the other screenshot, the due date is empty. Can't tell why that is :(

**Comment by jpralle** [comment]
I also recognized, the date is somehow broken in my Obsidian not, too. I guess while doin the post the sync intervall completed and it did sync the "NaN"s back.

![Bildschirmfoto 2023-06-21 um 16 36 56](https://github.com/HeroBlackInk/ultimate-todoist-sync-for-obsidian/assets/2845414/e5261b6c-8aa2-4919-82e1-4773cbf6bf93)

**Comment by jpralle** [comment]
Would be nice to get replies in a more friendly tone. When you dislike getting reports on your plugins usage, just let me know. I was just checking the releases in the readme, where it's missing. I will update to 1.0.42.

**Comment by jpralle** [comment]
1.0.42 does not sync the due date at all and stills breaks it inside Tasks plugin.

**Comment by HeroBlackInk** [comment]
Duedate  is a issue that has been discussed. I am impatient to answer the question repeatedly.

**Comment by HeroBlackInk** [comment]
I think you should confirm whether it is an existing problem before you ask a new question. As for the new problems you have encountered, no one else has encountered them so far. Unless a detailed reproduction process can be provided, it will not be processed.

**Comment by HeroBlackInk** [comment]
I developed a plugin for my own needs. I don't use the tasks plugin,and I have no obligation to meet your needs. I'm not your free customer service either.

**Comment by jpralle** [comment]
Which is ne the new one? I guess, I provided all the details so far.

No you're not free customer service. You're a developer with no intention of supporting something you put out in public. This is totally okay, but you should state so clearly or not put that stuff in the public Obsidian plugin repo, I think. And you could have saved yourself and me a lot of time, if you just stated that in the beginning. This half doing it and half not is not helping anyone.

**Comment by HeroBlackInk** [comment]
You are wasting my time. Every question you have raised in this issue has already been discussed by others. I don't have time to respond to a crybaby.

**Comment by HeroBlackInk** [comment]
If you encounter an undiscovered bug, I am happy to help. Please do not ask any duplicate questions.
