### ISSUE TITLE
Obsidian page links don't encode spaces

### ISSUE THREAD

**Issue by QuaCKeReD** [HeroBlackInk/ultimate-todoist-sync-for-obsidian#3]
Obsidian page links within the Todoist task doesn't encode non web safe characters;

![CleanShot 20230403 113548 HhAs5Ksr](https://user-images.githubusercontent.com/2767970/229485980-801931f3-ea1e-4524-8766-e343e13e4380.png)

**Comment by HeroBlackInk** [comment]
solved 6150bfdf214fc10470a5a4466a1bc35c45e5e6de

**Comment by QuaCKeReD** [comment]
maybe a combination of both? 😀

**Comment by HeroBlackInk** [comment]
This time should be no problem. 09b0cb39ea984cb5a3d0462e86dab20da8c31e12

**Comment by QuaCKeReD** [comment]
👍🏻

**Comment by QuaCKeReD** [comment]
Brilliant work on this plugin, just what I wanted with the integration
