### ISSUE TITLE
Checking off in Todoist remains unfinished in Obsidian

### ISSUE THREAD

**Issue by SecurityDog88** [HeroBlackInk/ultimate-todoist-sync-for-obsidian#30]
If I check off a task in Todoist, i.e. mark it as done, then perform the sync in Obsidian, I do get the message that the ID is closed in Todoist, but the task is not checked off in Obsidian. However, if I check off the task in Obsidian, the task is also immediately checked off in Todoist.

**Comment by HeroBlackInk** [comment]
You can try the latest version, where all synchronization has been automated and no longer requires manual clicking. It will automatically detect and synchronize in both directions. The old synchronization method has been abandoned, so you can try the latest version. 

It is a pre release, so there may be some unknown bugs.

**Comment by SecurityDog88** [comment]
Thansk, that helped :)
