### ISSUE TITLE
Read date with space as well

### ISSUE THREAD

**Issue by SecurityDog88** [HeroBlackInk/ultimate-todoist-sync-for-obsidian#31]
I would very much wish that a date is also read out when it is written as follows: ICON DATE
Meaning there is a space between the icon and the date.

I am using the Tasks plugin and it always automatically puts a space in between, so I have to manually change it so that it can be processed by your plugin.

**Comment by HeroBlackInk** [comment]
Custom date format will be added in the future.

**Comment by HeroBlackInk** [comment]
duplicated issue

**Comment by SecurityDog88** [comment]
Can you tell me, which File I have to change, that I can solve it for me at the moment? :)
I am not a programmer, but I give me best ;)

**Comment by HeroBlackInk** [comment]
download file `main.js`

replace `.obsidian/plugins/ultimate-todoist-sync/main.js`
