### ISSUE TITLE
Sync stopped working in latest version

### ISSUE THREAD

**Issue by mAAdhaTTah** [HeroBlackInk/ultimate-todoist-sync-for-obsidian#32]
Was running 1.0.36 and was able to create new tasks in my notes without issue. After upgrading to 1.0.39, the sync seems to have stopped working. I created a task in a note with the `#todoist` tag and it's not syncing to my inbox.

Let me know if you need more info.

**Comment by mAAdhaTTah** [comment]
I see the sync running in the console but nothing is getting synced. Also hitting the sync button in the settings doesn't sync the todo I added.

**Comment by HeroBlackInk** [comment]
The bug has been fixed, please upgrade to 1.0.40.

**Comment by mAAdhaTTah** [comment]
That did it, thank you!
