### ISSUE TITLE
启用了全库同步, 初始化同步后,成功了, 现在新建任务不自动同步了

### ISSUE THREAD

**Issue by musicleaf** [HeroBlackInk/ultimate-todoist-sync-for-obsidian#33]
<img width="721" alt="image" src="https://github.com/HeroBlackInk/ultimate-todoist-sync-for-obsidian/assets/35360006/714c6245-f3cc-4a4c-b725-a9242302fb59">

**Comment by HeroBlackInk** [comment]
请升级到1.0.40

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 酷口 ***@***.***>
发送时间: Saturday, June 10, 2023 9:26:07 AM
收件人: HeroBlackInk/ultimate-todoist-sync-for-obsidian ***@***.***>
抄送: Subscribed ***@***.***>
主题: [HeroBlackInk/ultimate-todoist-sync-for-obsidian] 启用了全库同步, 初始化同步后,成功了, 现在新建任务不自动同步了 (Issue #33)


[image]<https://user-images.githubusercontent.com/35360006/244839326-714c6245-f3cc-4a4c-b725-a9242302fb59.png>

―

**Comment by musicleaf** [comment]
> 请升级到1.0.40

是升级到了这个版本的

**Comment by HeroBlackInk** [comment]
要换行，否则插件不会检查新增的任务

**Comment by musicleaf** [comment]
都会换行的.
<img width="866" alt="image" src="https://github.com/HeroBlackInk/ultimate-todoist-sync-for-obsidian/assets/35360006/c4c91595-e8ad-40ba-9e3a-25b6a5b5d56f">

新建的一个任务,移动到另外一个笔记, 不更新了

**Comment by musicleaf** [comment]
以前修改了任务,马上就有提示, 现在修改了任务, 没有任何反应,特别是这篇笔记已经有任务的.

不知道哪里出问题了,是不是我们的笔记太多, 一次性全库同步,导致api给我限频了

**Comment by musicleaf** [comment]
<img width="828" alt="image" src="https://github.com/HeroBlackInk/ultimate-todoist-sync-for-obsidian/assets/35360006/d4a81adc-669c-4bf9-8068-f8bf7558532d">

我怎么修改,他都不同步过去: 修改文字, 换行,增加日期

**Comment by HeroBlackInk** [comment]
不支持在文件之间移动。

添加修改任务我测试没有问题，你的问题我无法复现。

如果你不能提供有助于解决bug的信息，我将不再回复。我不可能看着你的截图就能找出bug。

**Comment by HeroBlackInk** [comment]
有何问题需要注意，单个project不能超过300个task。超出之后无法添加。可能是这个原因导致的

**Comment by musicleaf** [comment]
那就是问题了. 我肯定超过300个任务了

**Comment by musicleaf** [comment]
这300个任务是仅仅是未完成的,还是 包括了已完成+未完成呢

**Comment by HeroBlackInk** [comment]
未完成

**Comment by musicleaf** [comment]
看了一下只有80个未完成，我在测试下是不是最多是80个是上限。

有什么日志可以提供给你的

**Comment by HeroBlackInk** [comment]
官网描述的是300个 Active tasks。
