### ISSUE TITLE
Some tasks, namely in the date, swap day with month.

### ISSUE THREAD

**Issue by SecurityDog88** [HeroBlackInk/ultimate-todoist-sync-for-obsidian#34]
I have the problem (1.0.40 installed) that the date changes constantly for some tasks. Then the day and the month are always swapped. A short time later a new sync comes, which corrects this again, and then another one comes, where it is swapped again.

The date is stored here as ICON YYYY-MM-DD.

**Comment by HeroBlackInk** [comment]
I can only help you if you exclude other plugin-related issues and provide a detailed process to reproduce the bug.

**Comment by SecurityDog88** [comment]
I disabled all plugins except of yours.

I create a new task,

"[ ] Touch Portal einrichten. 📅 2023-06-10 #Todoist"

A little moment of a few seconds later 

"Task XXX has changed. Due date was changed"
"Task updated"

- [ ] Touch Portal einrichten. 📅 2023-10-06 #Todoist  %%[todoist_id:: XXX]%%

**Comment by HeroBlackInk** [comment]
Unable to reproduce your issue.

**Comment by SecurityDog88** [comment]
Uninstalled your plugin and installed it again, now it seems finally to work.

**Comment by HeroBlackInk** [comment]
You may encounter new problems because uninstalling the plugin will result in the loss of task information saved in the database, but the task information in markdown is still there.

**Comment by SecurityDog88** [comment]
Ah the problem is back again. So nothing changed :(

**Comment by snoweater001** [comment]
![이미지 2023  6  10  오후 11 22](https://github.com/HeroBlackInk/ultimate-todoist-sync-for-obsidian/assets/136179544/08e014e9-8ae9-42ef-8471-80cba8f5fd67)

after i made a task and i did anything.
some message keep show -> due has changed.. -> task ... is updated -> due date was changed -> content was changed
![이미지 2023  6  10  오후 11 22 (1)](https://github.com/HeroBlackInk/ultimate-todoist-sync-for-obsidian/assets/136179544/51990875-00be-4ca9-9649-a8378587da13)


obsidian v1.3.5
Ultimate todoist sync 1.0.40

**Comment by SecurityDog88** [comment]
Have the problem with "nan-nan-nan" now too + the old problem, with the change of month>day>month>day.

![image](https://github.com/HeroBlackInk/ultimate-todoist-sync-for-obsidian/assets/135823938/9aa99944-e43d-4525-b3e2-87cb286fcda2)

**Comment by HeroBlackInk** [comment]
Please upgrade to version 1.0.41 and then check if the bug has been resolved.

**Comment by snoweater001** [comment]
@HeroBlackInk Thanks your working. 

After 1.0.41, New tasks are working properly.

but old existing tasks only can 'closed'..
when i modify task in obisidan -> todoist task is not change

**Comment by SecurityDog88** [comment]
Thanks for your work! Now your Plugin is working for me without issue.
