### ISSUE TITLE
I might be missing something...

### ISSUE THREAD

**Issue by timbruls** [HeroBlackInk/ultimate-todoist-sync-for-obsidian#37]
but does this plugin also have the ability to list a list of existing todoist tasks in my notes? I can add tasks, but I have not found a way to display them in a note?

**Comment by HeroBlackInk** [comment]
This is a sync plugin, not a GTD plugin.

**Comment by timbruls** [comment]
> This is a sync plugin, not a GTD plugin.

OK, so no displaying then, I will need a different plugin for that, I was just asking because I want to keep my number of plugins low. The sync option works like a charm so thanks for that!

**Comment by HeroBlackInk** [comment]
thanks
