### ISSUE TITLE
Make it work for canvas cards

### ISSUE THREAD

**Issue by bytes032** [HeroBlackInk/ultimate-todoist-sync-for-obsidian#38]
First of all, brilliant plugin and good job!

I would love to see it work for canvas cards, e.g.

![Screenshot 2023-07-05 at 6 58 05 AM](https://github.com/HeroBlackInk/ultimate-todoist-sync-for-obsidian/assets/122114333/5d0aaf80-e4c9-4ded-8e4f-57f9f5ccfe18)

Thanks for the hard work!

**Comment by HeroBlackInk** [comment]
Canvas view and markdown view are completely different. I am not sure if there are any obsidian APIs for canvas, and even if they exist, the required workload would be equivalent to rewriting an entirely new plugin.

**Comment by bytes032** [comment]
damn :/

thanks for the quick response <3
