### ISSUE TITLE
Request: Have a config that allows default tags for all linked tasks on a page

### ISSUE THREAD

**Issue by QuaCKeReD** [HeroBlackInk/ultimate-todoist-sync-for-obsidian#4]
Hi,
I work on notes that have front matter values matching a particular client and project

It would be good if there was a way to use front matter from a file;
- as default values for any tasks linked to todoist
- to specify whether all tasks should be linked into Todoist

i.e.
```
---
client: My Big Client
project: Secret Project
todoist_sync: true
---
```

Would turn this
```
- [ ] First project task 
```
into this, automatically
```
- [ ] First project task #todoist #My_Big_Client #Secret_Project 
```

**Comment by HeroBlackInk** [comment]
Thank you for your proposal, I will consider it carefully. Adding this feature is very simple. However, there are many other factors to consider and I hope the plugin can be kept as simple as possible.

**Comment by HeroBlackInk** [comment]
Now, this plugin can set default project for different file paths. 2ec7cba1d4645740e5161584aa21a4a5eca4cce3
