### ISSUE TITLE
Sync Tasks Without Direct Editing

### ISSUE THREAD

**Issue by julroger2013** [HeroBlackInk/ultimate-todoist-sync-for-obsidian#5]
I was amazed by how quickly this syncs tasks into Todoist!

I noticed that this plugin does not always sync tasks when the at-issue task is not directly edited. For instance, I often add tasks to a note by using Quickadd, which drops the task elsewhere in the note (in my case, at the very bottom of the note). 

It appears that if I do not actively edit the task (that is, by having my cursor inside the task within the relevant note), it does not sync to Todoist. However, as soon as I move my cursor into the relevant task to edit something, it immediately syncs to Todoist and adds a Todoist ID. 

Could your plugin be made to work so that it scans for tasks across the entire active note, rather than the portion currently being edited?

**Comment by HeroBlackInk** [comment]
If the task contains #todoist, you only need to click the sync button to synchronize all tasks of the current file (only for the file currently open in the window).

**Comment by julroger2013** [comment]
Ok, that makes sense. Thank you for the advice!

Could the sync button's function be added as a command palette option, too? Once it becomes accessible in the Command Palette, that opens up lots of hotkey & automation options.
