### ISSUE TITLE
ob上添加时间，偶尔不成功，win系统

### ISSUE THREAD

**Issue by putink** [HeroBlackInk/ultimate-todoist-sync-for-obsidian#7]
添加日期，除了以🗓️图标的形式，是否还可以用其他的方式？
因为在win上需要复制粘贴过去，有时候会导致添加不成功

**Comment by HeroBlackInk** [comment]
什么情况下会添加失败？

**Comment by putink** [comment]
![微信截图_20230414162753](https://user-images.githubusercontent.com/22392907/231989267-e20c11a9-5b93-4444-8b5a-a1a1d0398c7b.png)
win上的日历，默认是下面这种。你的那个日历图标，我是从git上面复制过去的

**Comment by HeroBlackInk** [comment]
修改当前line的task之后，光标要切换到下一行才会同步

**Comment by putink** [comment]
我感觉是这个图标📅 ，和你规则不匹配？ [使用你的那个日历🗓️图标是OK的，我用的插件tasks的日期图标📅不行。
![1](https://user-images.githubusercontent.com/22392907/232176718-596dd82c-6a0c-442b-a181-62f2c729869e.png)

**Comment by HeroBlackInk** [comment]
有空会修复的，你可以试一试用输入法的快捷键将图标保存。。

**Comment by putink** [comment]
辛苦，插件非常赞

**Comment by HeroBlackInk** [comment]
solved 73a17ddbc00999e6aabe2ea1b7125ede94b4c8cb
