### ISSUE TITLE
配合tasks的插件,是否可以将代表时间的emoji兼容🗓️,目前使用的是📅, 希望两个emoji都支持设置时间

### ISSUE THREAD

**Issue by musicleaf** [HeroBlackInk/ultimate-todoist-sync-for-obsidian#8]
目前todoist参加使用的emoji是📅, 
tasks使用的是🗓️
希望两个emoji都支持设置时间

目前两个图标只能使用一个, tasks生效, todoist就不生效,  todoist生效,tasks就不生效. 希望能将兼容

<img width="660" alt="image" src="https://user-images.githubusercontent.com/35360006/232313267-5a516c0d-5d8f-4319-ac02-0c7621048b52.png">

**Comment by HeroBlackInk** [comment]
solved 73a17ddbc00999e6aabe2ea1b7125ede94b4c8cb
