### ISSUE TITLE
[Feature Request] Exclude # When Syncing Tags to Todoist

### ISSUE THREAD

**Issue by julroger2013** [HeroBlackInk/ultimate-todoist-sync-for-obsidian#9]
I've noticed that, when trying to add one of my Todoist labels to a task in Obsidian for syncing purposes, the tag continues to have the # indicator once synced to Todoist. 

For instance, I use a "@Next" label inside to Todoist to designate tasks I wish to work on at the next opportunity. But if I put #Next on a task in Obsidian, the label that appears on the task in Todoist isn't @Next but rather @#Next. Could it be made so that the # character is not carried over when syncing from Obsidian to Todoist?

**Comment by etiennepellegrini** [comment]
Agreed, the extra `#` is annoying.
Moreover, my todoist tags are different from my Obsidian tags -- using `#` to identify tags on a task that will be sent to Todoist means I create new tags in Obsidian as well

It'd be great if the tag character could be an option -- I would like to use `@` for instance, which may solve the problem

**Comment by PixelPoxel** [comment]
+1 this will be helpful

**Comment by fabfrodo1** [comment]
+1 from me as well :-)

**Comment by HeroBlackInk** [comment]
Release 1.0.37-beta fixed this issue.
